version: "3.7"
services:
  postgres:
    container_name: exercise-postgres
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    ports:
      - "5432:5432"
  graphql-engine:
    container_name: exercise-hasura
    image: hasura/graphql-engine:v2.10.1
    env_file: .env
    ports:
      - "${HASURA_PORT}:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_PORT: ${HASURA_PORT}
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
volumes:
  db_data:
